version: "3.8"

services:
  bitnet-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app/main.py:/code/main.py
      - ./app/lib:/code/lib
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload", "--reload-dir", "/code/lib"]
